### ISSUE TITLE
Fix failing unit tests.

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/Akka.Persistence.PostgreSql#23]
Currently the following tests are failing:
- PostgreSqlJournalQuerySpec.Journal_queried_on_Manifest_returns_events_with_particular_manifest
- PostgreSqlJournalQuerySpec.Journal_queried_on_PersistenceIdRange_returns_events_for_particular_persistent_ids
- PostgreSqlJournalQuerySpec.Journal_queried_on_Timestamp_returns_events_occurred_after_or_equal_From_value
- PostgreSqlJournalQuerySpec.Journal_queried_on_Timestamp_returns_events_occurred_before_To_value
- PostgreSqlJournalQuerySpec.Journal_queried_on_Timestamp_returns_events_occurred_between_both_range_values
- PostgreSqlJournalQuerySpec.Journal_queried_using_multiple_hints_should_apply_all_of_them

These needs to be fixed.

**Comment by alexvaluyskiy** [comment]
These query tests aren't failing locally.

**Comment by Arkatufus** [comment]
Stale issue, this is fixed already.
