### ISSUE TITLE
Should implement all tests from the Persistence TCK

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/Akka.Persistence.PostgreSql#36]
This plugin should implement and pass all tests from the TCK. Right now its missing at least the Serialization specs. And maybe a few more.

Related: 
https://github.com/akkadotnet/akka.net/issues/3019

**Comment by Danthar** [comment]
The TCK can be found here: 
https://github.com/akkadotnet/akka.net/tree/dev/src/core/Akka.Persistence.TCK

**Comment by Arkatufus** [comment]
Already addressed in #78

**Comment by CumpsD** [comment]
@Arkatufus could you have a look at https://github.com/akkadotnet/Akka.Persistence.PostgreSql/pull/78#pullrequestreview-612316724 ?
