### ISSUE TITLE
PR49 breaks BYTEA snapshots

### ISSUE THREAD

**Issue by biggyspender** [akkadotnet/Akka.Persistence.PostgreSql#63]
I'm using my own custom protobuf serializer and have run into an issue where the correct manifest information is not stored correctly in the snapshot store.

I've isolated the problem to:

https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/pull/49

which overrides the behaviour in [`AbstractQueryExecutor`](https://github.com/akkadotnet/akka.net/blob/8f0bb3f6747309a1b245bafb17d4b55f5d8c5b29/src/contrib/persistence/Akka.Persistence.Sql.Common/Snapshot/QueryExecutor.cs#L350) from

            if (serializer is SerializerWithStringManifest)
            {
                manifest = ((SerializerWithStringManifest)serializer).Manifest(snapshot);
            }
            else
            {
                if (serializer.IncludeManifest)
                {
                    manifest = snapshotType.TypeQualifiedName();
                }
            }

to the following in [`PostgreSqlQueryExecutor`](https://github.com/biggyspender/Akka.Persistence.PostgreSql/blob/186d71991456871850619c60965ac338cdb792c0/src/Akka.Persistence.PostgreSql/Snapshot/PostgreSqlQueryExecutor.cs#L120) :

            if (serializer is SerializerWithStringManifest)
            {
                manifest = ((SerializerWithStringManifest)serializer).Manifest(snapshot);
            }
            else if (!serializer.IncludeManifest) \\ <-- this test has been flipped
            {
                manifest = snapshotType.TypeQualifiedName();
            }

This is plainly wrong, and while it may fix JSON issues specific to the JSON implementation of `Akka.Persistence.PostgreSql`, when using one's own serialization scheme, ultimately causes snapshots to be stored without manifest information, which should (in my case) be the string : `Akka.Persistence.Fsm.PersistentFSM+PersistentFSMSnapshot`1[[SomeCustomStateType]], Akka.Persistence`. 

This causes divergent behaviour from other snapshot/journal plugins, such as sqlite, which, by relying on the correct base class implementation, successfully persist and restore these snapshots.

**Comment by biggyspender** [comment]
https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/pull/64 attempts to address this issue (only for BYTEA payloads) without treading on the feet of the commit that made this change.

**Comment by Horusiath** [comment]
Yes, now I see, I've merged PR #49 too fast - there are several issues with it:

1. It assumes that upon reading manifest is always a type name, and will [try to load type based on it](https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/blob/9a2e540e3fa621d72d88bc63aef4742d3baccdf7/src/Akka.Persistence.PostgreSql/Snapshot/PostgreSqlQueryExecutor.cs#L143), which is not always true (quite often `SerializerWithStringManifest` is just a single letter used to compress later type recognition, almost all protobuf serializers we have, works this way).
2. While writing, manifest should always be included (so [this check](https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/blob/9a2e540e3fa621d72d88bc63aef4742d3baccdf7/src/Akka.Persistence.PostgreSql/Snapshot/PostgreSqlQueryExecutor.cs#L124) is not necessary) - even if serializer has `IncludeManifest` set to false, we still want to know what was the type of a given object - very few serializers know how to recognize correct type without that info, and for others: this change may break them.

**Comment by biggyspender** [comment]
@Horusiath It seems that the issues extend beyond what I'd be comfortable fixing. https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/pull/64 works for me, but from the perspective of your diagnosis, https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/pull/64 is a little short-sighted.

Would be great to move back from my fork to the nuget package, so keen to see a fix in place soon.

Thanks

**Comment by Arkatufus** [comment]
The method being discussed isn't being overriden anymore.

**Comment by CumpsD** [comment]
It still is in Snapshots:

https://github.com/akkadotnet/Akka.Persistence.PostgreSql/blob/dev/src/Akka.Persistence.PostgreSql/Snapshot/PostgreSqlQueryExecutor.cs#L122-L130

It isn't in journal. But this issue mentioned snapshots in the title.
