### ISSUE TITLE
Used table format leaks to SnapshotOffer

### ISSUE THREAD

**Issue by beachwalker** [akkadotnet/Akka.Persistence.PostgreSql#65]
When trying to cast type from snapshot payload the content depends upon configured column type (JSON or BYTEA).
The offer payload should be already deserialized, instead now you have to take care inside PersitentActor Recover method.

**Comment by Horusiath** [comment]
Hi @beachwalker could you show the sample, you're using?

**Comment by Arkatufus** [comment]
@beachwalker It would be helpful if you can provide us a gist of your code because our unit tests shows that snapshot serialization works just fine.

**Comment by Arkatufus** [comment]
@beachwalker Closing this issue for now, please reopen it if you're still experiencing problem.
