### ISSUE TITLE
Akka 1.4 support

### ISSUE THREAD

**Issue by jblackburn21** [akkadotnet/Akka.Persistence.PostgreSql#73]
I'm trying to use this library with Akka 1.4.14 and .net5.0, but receive this exception when replaying events

`System.MissingMethodException: Method not found: 'Void Akka.Persistence.Persistent..ctor(System.Object, Int64, System.String, System.String, Boolean, Akka.Actor.IActorRef, System.String)'.`

I pulled in the package locally, upgraded to netstandard2.0 and updated its dependencies, and my testing has been successful so far. Will you accept a pr with these updates?

**Comment by IgorFedchenko** [comment]
All right, v1.4.14 was added in this PR: https://github.com/akkadotnet/Akka.Persistence.PostgreSql/pull/78

The error above is due to binary incompatibility of the core and plugin packages - wait for the next release of Akka.Persistence.Postresql, it should work correctly with Akka v1.4.14 packages
